config/routes.rb
Ndpsige::Application.routes.draw do
  resources :proveedors

  resources :stocks

  resources :articulos

  resources :colaboradors

  resources :sales

  resources :medio_pagos


  resources :clientes

  resources :cajeros

  resources :productos

  resources :tipo_productos

  root :to => "home#index"
  devise_for :users, :path_prefix => 'auth'
end

app/models/stock.rb
# == Schema Information
#
# Table name: stocks
#
#  id              :integer          not null, primary key
#  articulo_id     :integer
#  cantidad        :float
#  precio_unitario :float
#  precio_total    :float
#  user_id         :integer
#  empresa_id      :integer
#  fecha_compra    :date
#  created_at      :datetime
#  updated_at      :datetime
#

class Stock < ActiveRecord::Base
  belongs_to :articulo
  belongs_to :user
  belongs_to :empresa
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to stocks_path, notice: 'Stock was successfully created.' }
        format.json { render action: 'show', status: :created, location: @stock }
      else
        format.html { render action: 'new' }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:articulo_id, :cantidad, :precio_unitario, :precio_total, :user_id, :empresa_id, :fecha_compra)
    end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_form.html.erb
  <%= simple_form_for(@stock, :html => {:class=>"form-horizontal"}) do |f| %>
            <%= f.error_notification %>
            <div class="form-inputs">
              <%= f.association :articulo,:label_method => :nombre,:label=>"Artículo" %>
              <%= f.input :cantidad ,:label=>"Cantidad", :as => :string%>
              <%= f.input :precio_unitario ,:label=>"Precio Unitario", :as => :string%>
              <%= f.input :precio_total,:label=>"Precio Total", :as => :string %>
              <%= f.input :fecha_compra, :label=>"Fecha Compra", :default => Date.today, :as => :date,  :order=> [:day, :month, :year] %>
            </div>
            <div class="form-actions bg-silver">
              <%= link_to 'Atrás', :back, :class=>"btn"  %>
              <%= f.button :submit, "Enviar", :class=>"btn btn-primary" %>
            </div>
            <% end %>

app/views/stocks/edit.html.erb
<!-- content header -->
<header class="content-header">
  
  <!-- content title-->
  <div class="page-header"><h1>Editar Stock</h1></div>
  <!-- content breadcrumb -->
  <ul class="breadcrumb breadcrumb-inline">
    <li><a href="#">Inicio</a> <span class="divider"><i class="aweso-angle-right"></i></span></li>
    <li><a href="#">Inventario</a> <span class="divider"><i class="aweso-angle-right"></i></span></li>
    <li class="active">Editar Stock</li>
  </ul>
  </header> <!--/ content header -->
  
  
  <!-- content page -->
  <article class="content-page">
  <!-- main page, you're application here -->
  <div class="main-page">
    <div class="content-inner">
      <!-- FORM HORIZONTAL
      ================================================== -->
      <!-- widget form horizontal -->
      <div class="widget border-cyan" id="widget-horizontal">
        <!-- widget header -->
        <div class="widget-header bg-cyan">
          <!-- widget icon -->
          <div class="widget-icon"><i class="aweso-edit"></i></div>
          <!-- widget title -->
          <h4 class="widget-title">Formulario</h4>
          <!-- widget action, you can also use btn, btn-group, nav-tabs or nav-pills (also support dropdown). enjoy! -->
          <div class="widget-action color-cyan">
            <button data-toggle="collapse" data-collapse="#widget-horizontal" class="btn">
            <i class="aweso-minus" data-toggle-icon="aweso-minus aweso-plus"></i>
            </button>
          </div>
          </div><!-- /widget header -->
          <!-- widget content -->
          <div class="widget-content">
<%= render 'form' %>
            </div><!-- /widget content -->
            </div> <!-- /widget form horizontal -->
            </div><!-- /content-inner-->
            </div><!-- /main-page-->
            </article> <!-- /content page -->

app/views/stocks/index.html.erb
<!-- content header -->
<header class="content-header">
  <!-- content action (optional)-->
  <ul class="content-action pull-right">
    
    <li>  <%= link_to "Agregar Stock", new_stock_path, :class=>"btn btn-link" %></li>
    <li>  <%= link_to "Agregar Artículo", new_articulo_path, :class=>"btn btn-link" %></li>
    <li>  <%= link_to "Agregar Proveedor", new_proveedor_path, :class=>"btn btn-link" %></li>
    
    </ul> <!-- /content action -->
    <!-- content title-->
    <div class="page-header"><h1>Inventario de Stock</h1></div>
    <!-- content breadcrumb -->
    <ul class="breadcrumb breadcrumb-inline">
      <li><a href="#">Inicio</a> <span class="divider"><i class="aweso-angle-right"></i></span></li>
      <li class="active">Inventario</li>
    </ul>
    </header> <!--/ content header -->
    
    
    <!-- content page -->
    <article class="content-page">
    <!-- main page, you're application here -->
    <div class="main-page">
      <div class="content-inner">
        <!-- widget datatables #1 -->
        <div class="widget border-cyan" id="widget-datatables1">
          <!-- widget header -->
          <div class="widget-header bg-cyan">
            <!-- widget icon -->
            <div class="widget-icon"><i class="aweso-table"></i></div>
            <!-- widget title -->
            <h4 class="widget-title">Listado de inventario</h4>
            <!-- widget action, you can also use btn, btn-group, nav-tabs or nav-pills (also support dropdown). enjoy! -->
            <div class="widget-action color-cyan">
              <button data-toggle="collapse" data-collapse="#widget-datatables1" class="btn">
              <i class="aweso-minus" data-toggle-icon="aweso-minus aweso-plus"></i>
              </button>
            </div>
            </div><!-- /widget header -->
            <!-- widget content -->
            <div class="widget-content">
              <table class="table table-bordered">
                <thead>
                  <tr>
                    
                    <th>Articulo</th>
                    <th>Cantidad</th>
                    
                    <th>Fecha compra</th>
                    <th class="span1"></th>
                    
                  </tr>
                </thead>
                <tbody>
                  <% @stocks.each do |stock| %>
                  <tr>
                    <td><%= stock.articulo.nombre if stock.articulo %></td>
                    <td><%= stock.cantidad.presence %></td>
                
                    <td><%= stock.fecha_compra.presence %></td>
                    <td>
                      <div class="btn-group">
                        <%= link_to 'Ver', stock, :class=>"btn btn-primary" %>
                        <%= link_to 'Editar', edit_stock_path(stock), :class=>"btn btn-warning" %>
                        <%= link_to 'Eliminar', stock, method: :delete, data: { confirm: 'Seguro?' }, :class=>"btn btn-danger" %>
                      </div>
                    </td>
                  </tr>
                </tr>
                <%end%>
              </tbody>
            </table>
            </div><!-- /widget content -->
            </div> <!-- /widget datatables #1 -->
            
            
            </div><!-- /content-inner-->
            </div><!-- /main-page-->
            <div class="clearfix"></div>
            </article> <!-- /content page -->

app/views/stocks/new.html.erb
<!-- content header -->
<header class="content-header">
  
  <!-- content title-->
  <div class="page-header"><h1>Agregar Stock</h1></div>
  <!-- content breadcrumb -->
  <ul class="breadcrumb breadcrumb-inline">
    <li><a href="#">Inicio</a> <span class="divider"><i class="aweso-angle-right"></i></span></li>
    <li><a href="#">Inventario</a> <span class="divider"><i class="aweso-angle-right"></i></span></li>
    <li class="active">Agregar Stock</li>
  </ul>
  </header> <!--/ content header -->
  
  
  <!-- content page -->
  <article class="content-page">
  <!-- main page, you're application here -->
  <div class="main-page">
    <div class="content-inner">
      <!-- FORM HORIZONTAL
      ================================================== -->
      <!-- widget form horizontal -->
      <div class="widget border-cyan" id="widget-horizontal">
        <!-- widget header -->
        <div class="widget-header bg-cyan">
          <!-- widget icon -->
          <div class="widget-icon"><i class="aweso-edit"></i></div>
          <!-- widget title -->
          <h4 class="widget-title">Formulario</h4>
          <!-- widget action, you can also use btn, btn-group, nav-tabs or nav-pills (also support dropdown). enjoy! -->
          <div class="widget-action color-cyan">
            <button data-toggle="collapse" data-collapse="#widget-horizontal" class="btn">
            <i class="aweso-minus" data-toggle-icon="aweso-minus aweso-plus"></i>
            </button>
          </div>
          </div><!-- /widget header -->
          <!-- widget content -->
          <div class="widget-content">
<%= render 'form' %>
            </div><!-- /widget content -->
            </div> <!-- /widget form horizontal -->
            </div><!-- /content-inner-->
            </div><!-- /main-page-->
            </article> <!-- /content page -->

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Articulo:</strong>
  <%= @stock.articulo %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @stock.cantidad %>
</p>

<p>
  <strong>Precio unitario:</strong>
  <%= @stock.precio_unitario %>
</p>

<p>
  <strong>Precio total:</strong>
  <%= @stock.precio_total %>
</p>

<p>
  <strong>User:</strong>
  <%= @stock.user %>
</p>

<p>
  <strong>Empresa:</strong>
  <%= @stock.empresa %>
</p>

<p>
  <strong>Fecha compra:</strong>
  <%= @stock.fecha_compra %>
</p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>