config/routes.rb
Ndpsige::Application.routes.draw do
  resources :proveedors

  resources :stocks

  resources :articulos

  resources :colaboradors

  resources :sales

  resources :medio_pagos


  resources :clientes

  resources :cajeros

  resources :productos

  resources :tipo_productos

  root :to => "home#index"
  devise_for :users, :path_prefix => 'auth'
end

app/models/producto.rb
# == Schema Information
#
# Table name: productos
#
#  id              :integer          not null, primary key
#  nombre          :string(255)
#  tipoProducto_id :integer
#  stock           :integer
#  precio          :float
#  created_at      :datetime
#  updated_at      :datetime
#  empresa_id      :integer
#

class Producto < ActiveRecord::Base
  belongs_to :tipoProducto
  belongs_to :empresa
  has_many :productosales
  has_many :sales, through: :productosale
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]
    before_filter :authenticate_user!
  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.all
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render action: 'show', status: :created, location: @producto }
      else
        format.html { render action: 'new' }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:nombre, :tipoProducto_id, :stock, :precio)
    end
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/productos/_form.html.erb
<%= simple_form_for(@producto, :html => {:class=>"form-horizontal"}) do |f| %>
<%= f.error_notification %>
<div class="form-inputs">
  <%= f.input :nombre %>
  <%= f.association :tipoProducto, :label_method=> :nombre %>
  <%= f.input :stock, :as=> :string %>
  <%= f.input :precio , :as=> :string%>
</div>
<div class="form-actions bg-silver">
  <%= link_to 'Atrás', :back, :class=>"btn"  %>
  <%= f.button :submit, "Enviar", :class=>"btn btn-primary" %>
</div>
<% end %>

app/views/productos/edit.html.erb
<!-- content header -->
<header class="content-header">
	
	<!-- content title-->
	<div class="page-header"><h1>Editar Producto</h1></div>
	<!-- content breadcrumb -->
	<ul class="breadcrumb breadcrumb-inline">
		<li><a href="#">Inicio</a> <span class="divider"><i class="aweso-angle-right"></i></span></li>
		<li><a href="#">Productos</a> <span class="divider"><i class="aweso-angle-right"></i></span></li>
		<li class="active">Editar</li>
	</ul>
	</header> <!--/ content header -->
	
	
	<!-- content page -->
	<article class="content-page">
	<!-- main page, you're application here -->
	<div class="main-page">
		<div class="content-inner">
			<!-- FORM HORIZONTAL
			================================================== -->
			<!-- widget form horizontal -->
			<div class="widget border-cyan" id="widget-horizontal">
				<!-- widget header -->
				<div class="widget-header bg-cyan">
					<!-- widget icon -->
					<div class="widget-icon"><i class="aweso-edit"></i></div>
					<!-- widget title -->
					<h4 class="widget-title">Formulario</h4>
					<!-- widget action, you can also use btn, btn-group, nav-tabs or nav-pills (also support dropdown). enjoy! -->
					<div class="widget-action color-cyan">
						<button data-toggle="collapse" data-collapse="#widget-horizontal" class="btn">
						<i class="aweso-minus" data-toggle-icon="aweso-minus aweso-plus"></i>
						</button>
					</div>
					</div><!-- /widget header -->
					<!-- widget content -->
					<div class="widget-content">
						
						<%= render 'form' %>
						</div><!-- /widget content -->
						</div> <!-- /widget form horizontal -->
						</div><!-- /content-inner-->
						</div><!-- /main-page-->
						</article> <!-- /content page -->

app/views/productos/index.html.erb
  <!-- content header -->
  <header class="content-header">
    <!-- content action (optional)-->
    <ul class="content-action pull-right">
      
      <li>  <%= link_to "Nuevo Producto", new_producto_path, :class=>"btn btn-link" %></li>
      
      </ul> <!-- /content action -->
      <!-- content title-->
      <div class="page-header"><h1>Productos</h1></div>
      <!-- content breadcrumb -->
      <ul class="breadcrumb breadcrumb-inline">
        <li><a href="#">Inicio</a> <span class="divider"><i class="aweso-angle-right"></i></span></li>
        <li class="active">Productos</li>
      </ul>
      </header> <!--/ content header -->
      
      
      <!-- content page -->
      <article class="content-page">
      <!-- main page, you're application here -->
      <div class="main-page">
        <div class="content-inner">
          <!-- widget datatables #1 -->
          <div class="widget border-cyan" id="widget-datatables1">
            <!-- widget header -->
            <div class="widget-header bg-cyan">
              <!-- widget icon -->
              <div class="widget-icon"><i class="aweso-table"></i></div>
              <!-- widget title -->
              <h4 class="widget-title">Listado de productos</h4>
              <!-- widget action, you can also use btn, btn-group, nav-tabs or nav-pills (also support dropdown). enjoy! -->
              <div class="widget-action color-cyan">
                <button data-toggle="collapse" data-collapse="#widget-datatables1" class="btn">
                <i class="aweso-minus" data-toggle-icon="aweso-minus aweso-plus"></i>
                </button>
              </div>
              </div><!-- /widget header -->
              <!-- widget content -->
              <div class="widget-content">
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      
                      <th>Nombre</th>
                      <th>Tipoproducto</th>
                      <th>Stock</th>
                      <th>Precio</th>
                      <th class="span1"></th>
                      
                    </tr>
                  </thead>
                  <tbody>
                    <% @productos.each do |producto| %>
                    <tr>
                      <td><%= producto.nombre %></td>
                      <td><%= producto.tipoProducto.nombre %></td>
                      <td><%= producto.stock %></td>
                      <td><%= number_to_currency(producto.precio) %></td>
                      <td>
                        <div class="btn-group">
                          <%= link_to 'Ver', producto, :class=>"btn btn-primary" %>
                          <%= link_to 'Editar', edit_producto_path(producto), :class=>"btn btn-warning" %>
                          <%= link_to 'Eliminar', producto, method: :delete, data: { confirm: 'Seguro?' }, :class=>"btn btn-danger" %>
                        </div>
                      </td>
                    </tr>
                  </tr>
                  <%end%>
                </tbody>
              </table>
              </div><!-- /widget content -->
              </div> <!-- /widget datatables #1 -->
              
              
              </div><!-- /content-inner-->
              </div><!-- /main-page-->
              <div class="clearfix"></div>
              </article> <!-- /content page -->

app/views/productos/new.html.erb
<!-- content header -->
<header class="content-header">
	
	<!-- content title-->
	<div class="page-header"><h1>Agregar Producto</h1></div>
	<!-- content breadcrumb -->
	<ul class="breadcrumb breadcrumb-inline">
		<li><a href="#">Inicio</a> <span class="divider"><i class="aweso-angle-right"></i></span></li>
		<li><a href="#">Productos</a> <span class="divider"><i class="aweso-angle-right"></i></span></li>
		<li class="active">Agregar</li>
	</ul>
	</header> <!--/ content header -->
	
	
	<!-- content page -->
	<article class="content-page">
	<!-- main page, you're application here -->
	<div class="main-page">
		<div class="content-inner">
			<!-- FORM HORIZONTAL
			================================================== -->
			<!-- widget form horizontal -->
			<div class="widget border-cyan" id="widget-horizontal">
				<!-- widget header -->
				<div class="widget-header bg-cyan">
					<!-- widget icon -->
					<div class="widget-icon"><i class="aweso-edit"></i></div>
					<!-- widget title -->
					<h4 class="widget-title">Formulario</h4>
					<!-- widget action, you can also use btn, btn-group, nav-tabs or nav-pills (also support dropdown). enjoy! -->
					<div class="widget-action color-cyan">
						<button data-toggle="collapse" data-collapse="#widget-horizontal" class="btn">
						<i class="aweso-minus" data-toggle-icon="aweso-minus aweso-plus"></i>
						</button>
					</div>
					</div><!-- /widget header -->
					<!-- widget content -->
					<div class="widget-content">
						
						<%= render 'form' %>
						</div><!-- /widget content -->
						</div> <!-- /widget form horizontal -->
						</div><!-- /content-inner-->
						</div><!-- /main-page-->
						</article> <!-- /content page -->

app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @producto.nombre %>
</p>

<p>
  <strong>Tipoproducto:</strong>
  <%= @producto.tipoProducto %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @producto.stock %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @producto.precio %>
</p>

<%= link_to 'Edit', edit_producto_path(@producto) %> |
<%= link_to 'Back', productos_path %>