config/routes.rb
Ndpsige::Application.routes.draw do
  resources :proveedors

  resources :stocks

  resources :articulos

  resources :colaboradors

  resources :sales

  resources :medio_pagos


  resources :clientes

  resources :cajeros

  resources :productos

  resources :tipo_productos

  root :to => "home#index"
  devise_for :users, :path_prefix => 'auth'
end

app/models/sale.rb
# == Schema Information
#
# Table name: sales
#
#  id            :integer          not null, primary key
#  cajero_id     :integer
#  cliente_id    :integer
#  medioPago_id  :integer
#  user_id       :integer
#  created_at    :datetime
#  updated_at    :datetime
#  fecha         :datetime
#  anulado       :boolean
#  telefonico    :boolean
#  pagopendiente :boolean          default(FALSE), not null
#  boleta        :string(255)
#  total         :float
#

class Sale < ActiveRecord::Base
  belongs_to :cajero
  belongs_to :cliente
  belongs_to :medioPago
  belongs_to :user

  has_many :productosales
  has_many :productos, through: :productosale

  accepts_nested_attributes_for :productosales, allow_destroy: true
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]
    before_filter :authenticate_user!
  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
    @productos = current_user.empresa.productos
    @cajeros = current_user.empresa.cajeros
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to sales_path, notice: 'Sale was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sale }
      else
        format.html { render action: 'new' }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:cajero_id, :cliente_id, :medioPago_id, :pagopendiente, :user_id, productosales_attributes: [ :producto_id, :cantidad])
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
                                  <%= simple_form_for(@sale, :html => {:class=>"form-horizontal"}) do |f| %>
                                    <%= f.error_notification %>

                                    <div class="form-inputs">
                                     
                                      <%= f.association :cliente,:prompt=> "Seleccione", :label_method=> :nombre,:hint=> "#{link_to 'Registrar Nuevo',new_cliente_path, :target=> '_blank' }" %>
                                        <%= f.input :boleta, :label=> "Boleta" %>
                                         <%= f.association :medioPago, :label=> "Medio de Pago" , :label_method=> :nombre,:prompt=> "Seleccione"%>
                                       <%= f.input :pagopendiente, :label=> "Pago Pendiente" %>
                                       <%= f.input :fecha, :label=>"Fecha", :default => Date.today, :as => :date,  :order=> [:day, :month, :year],:input_html => { :style => "width: 140px" } %>
                                      <hr>
                                      <h4 >Productos</h4>
                           
                                      <div class="items">
                                        <%= f.nested_fields_for :productosales do |f|
                                              render 'producto', f: f
                                            end -%>
                                      </div>
                                      <a href="#" class="add">Agregar</a>




                                    </div>

                                    <div class="form-actions bg-silver">

                                      <%= f.button :submit, "Enviar", :class=>"btn btn-primary" %>
                                       <%= link_to 'Atrás', :back, :class=>"btn"  %>
                                    </div>
                                  <% end %>

app/views/sales/_producto.html.erb
<fieldset class="item">
	
	<%= f.association :producto, :label_method=> :nombre, :collection=> @productos,:prompt =>"Seleccione"   %>
	<%= f.input :cantidad, :as => :string, :label=> "Cantidad",:hint=> "#{link_to 'Eliminar', :html=> {:class=> 'remove' }}" %>
	<%= f.hidden_field :id %>
	<%= f.hidden_field :_destroy %>
</fieldset>

app/views/sales/edit.html.erb
<h1>Editing sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
                <!-- content header -->
                <header class="content-header">
                    <!-- content action (optional)-->
                    <ul class="content-action pull-right">
           
                    <li>  <%= link_to "Nueva Venta", new_sale_path, :class=>"btn btn-link" %></li>
         
                    </ul> <!-- /content action -->

                    <!-- content title-->
                    <div class="page-header"><h1>Ventas</h1></div>

                    <!-- content breadcrumb -->
                    <ul class="breadcrumb breadcrumb-inline">
                        <li><a href="#">Inicio</a> <span class="divider"><i class="aweso-angle-right"></i></span></li>
                        <li class="active">Ventas</li>
                    </ul>
                </header> <!--/ content header -->
                
                
                <!-- content page -->
                <article class="content-page">
                    <!-- main page, you're application here -->
                    <div class="main-page">
                        <div class="content-inner">
                            <!-- widget datatables #1 -->
                            <div class="widget border-cyan" id="widget-datatables1">
                                <!-- widget header -->
                                <div class="widget-header bg-cyan">
                                    <!-- widget icon -->
                                    <div class="widget-icon"><i class="aweso-table"></i></div>
                                    <!-- widget title -->
                                    <h4 class="widget-title">Listado ventas</h4>
                                    <!-- widget action, you can also use btn, btn-group, nav-tabs or nav-pills (also support dropdown). enjoy! -->
                                    <div class="widget-action color-cyan">
                                        <button data-toggle="collapse" data-collapse="#widget-datatables1" class="btn">
                                            <i class="aweso-minus" data-toggle-icon="aweso-minus aweso-plus"></i>
                                        </button>
                                    </div>
                                </div><!-- /widget header -->

                                <!-- widget content -->
                               <div class="widget-content">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr>
                                                        <th>#</th>
                                                        <th>Fecha</th>
                                                        <th>Cliente</th>
                                                        <th>Boleta</th>
                                                        <th>Medio Pago</th>
                                                        <th>Usuario</th>
                                                         <th>$Total</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                  <% @sales.each do |sale| %>
                                                  <% if sale.pagopendiente %>
                                                    <tr class="warning">
                                                        <%else%>
                                                        <tr>
                                                        <%end%>

                                                        <td><%= sale.id %></td>
                                                        <td><%= (l sale.fecha, :format => :fecha)  if sale.fecha%></td>
                                                        <td><%= sale.cliente.nombre if sale.cliente %></td>
                                                        <td><%= sale.boleta %></td>
                                                        
                                                        <td><%= sale.medioPago.nombre if sale.medioPago %></td>
                                                         <td><%= sale.user.nombre if sale.user %></td>
                                                        <td><%= number_to_currency(sale.total) %></td>
                                                    </tr>
                                                    <%end%>
                                                    </tbody>
                                            </table>
                                        </div><!-- /widget content -->
                            </div> <!-- /widget datatables #1 -->



                   

             



                        </div><!-- /content-inner-->
                    </div><!-- /main-page-->

                    <div class="clearfix"></div>
                </article> <!-- /content page -->

app/views/sales/new.html.erb
                <!-- content header -->
                <header class="content-header">
       

                    <!-- content title-->
                    <div class="page-header"><h1>Ingreso de Venta</h1></div>

                    <!-- content breadcrumb -->
                    <ul class="breadcrumb breadcrumb-inline">
                        <li><a href="#">Inicio</a> <span class="divider"><i class="aweso-angle-right"></i></span></li>
                        <li class="active">Venta</li>
                    </ul>
                </header> <!--/ content header -->
                
                
                <!-- content page -->
                <article class="content-page">
                    <!-- main page, you're application here -->
                    <div class="main-page">
                        <div class="content-inner">
                            <!-- FORM HORIZONTAL
                            ================================================== -->
                            <!-- widget form horizontal -->
                            <div class="widget border-cyan" id="widget-horizontal">
                                <!-- widget header -->
                                <div class="widget-header bg-cyan">
                                    <!-- widget icon -->
                                    <div class="widget-icon"><i class="aweso-edit"></i></div>
                                    <!-- widget title -->
                                    <h4 class="widget-title">Formulario</h4>
                                    <!-- widget action, you can also use btn, btn-group, nav-tabs or nav-pills (also support dropdown). enjoy! -->
                                    <div class="widget-action color-cyan">
                                        <button data-toggle="collapse" data-collapse="#widget-horizontal" class="btn">
                                            <i class="aweso-minus" data-toggle-icon="aweso-minus aweso-plus"></i>
                                        </button>
                                    </div>
                                </div><!-- /widget header -->

                                <!-- widget content -->
                                <div class="widget-content">
                                 <%= render 'form' %>



                                </div><!-- /widget content -->
                            </div> <!-- /widget form horizontal -->



                        </div><!-- /content-inner-->
                    </div><!-- /main-page-->

                </article> <!-- /content page -->

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cajero:</strong>
  <%= @sale.cajero %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @sale.cliente %>
</p>

<p>
  <strong>Mediopago:</strong>
  <%= @sale.medioPago %>
</p>

<p>
  <strong>User:</strong>
  <%= @sale.user %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>