config/routes.rb
Ndpsige::Application.routes.draw do
  resources :proveedors

  resources :stocks

  resources :articulos

  resources :colaboradors

  resources :sales

  resources :medio_pagos


  resources :clientes

  resources :cajeros

  resources :productos

  resources :tipo_productos

  root :to => "home#index"
  devise_for :users, :path_prefix => 'auth'
end

app/models/articulo.rb
# == Schema Information
#
# Table name: articulos
#
#  id           :integer          not null, primary key
#  nombre       :string(255)
#  precio       :float
#  empresa_id   :integer
#  created_at   :datetime
#  updated_at   :datetime
#  proveedor_id :integer
#

class Articulo < ActiveRecord::Base
  belongs_to :empresa
  belongs_to :proveedor

  
end

app/models/cajero.rb
# == Schema Information
#
# Table name: cajeros
#
#  id         :integer          not null, primary key
#  nombre     :string(255)
#  created_at :datetime
#  updated_at :datetime
#  empresa_id :integer
#

class Cajero < ActiveRecord::Base

	belongs_to :empresa
	
end

app/models/cliente.rb
# == Schema Information
#
# Table name: clientes
#
#  id         :integer          not null, primary key
#  nombre     :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Cliente < ActiveRecord::Base
end

app/models/colaborador.rb
# == Schema Information
#
# Table name: colaboradors
#
#  id         :integer          not null, primary key
#  nombre     :string(255)
#  telefono   :string(255)
#  email      :string(255)
#  empresa_id :integer
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Colaborador < ActiveRecord::Base
  belongs_to :empresa
  belongs_to :user
end

app/models/empresa.rb
# == Schema Information
#
# Table name: empresas
#
#  id         :integer          not null, primary key
#  nombre     :string(255)
#  ciudad     :string(255)
#  email      :string(255)
#  telefono   :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Empresa < ActiveRecord::Base

  has_many :colaboradors
  has_many :users
  has_many :productos
  has_many :stocks
  has_many :articulos
  has_many :cajeros
end

app/models/medio_pago.rb
# == Schema Information
#
# Table name: medio_pagos
#
#  id         :integer          not null, primary key
#  nombre     :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class MedioPago < ActiveRecord::Base
has_many :ventas
end

app/models/producto.rb
# == Schema Information
#
# Table name: productos
#
#  id              :integer          not null, primary key
#  nombre          :string(255)
#  tipoProducto_id :integer
#  stock           :integer
#  precio          :float
#  created_at      :datetime
#  updated_at      :datetime
#  empresa_id      :integer
#

class Producto < ActiveRecord::Base
  belongs_to :tipoProducto
  belongs_to :empresa
  has_many :productosales
  has_many :sales, through: :productosale
end

app/models/productosale.rb
# == Schema Information
#
# Table name: productosales
#
#  id          :integer          not null, primary key
#  producto_id :integer
#  sale_id     :integer
#  created_at  :datetime
#  updated_at  :datetime
#  cantidad    :float
#

class Productosale < ActiveRecord::Base
  belongs_to :producto
  belongs_to :sale
  
end

app/models/proveedor.rb
# == Schema Information
#
# Table name: proveedors
#
#  id         :integer          not null, primary key
#  nombre     :string(255)
#  telefono   :string(255)
#  email      :string(255)
#  web        :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Proveedor < ActiveRecord::Base

	has_many :articulos
end

app/models/sale.rb
# == Schema Information
#
# Table name: sales
#
#  id            :integer          not null, primary key
#  cajero_id     :integer
#  cliente_id    :integer
#  medioPago_id  :integer
#  user_id       :integer
#  created_at    :datetime
#  updated_at    :datetime
#  fecha         :datetime
#  anulado       :boolean
#  telefonico    :boolean
#  pagopendiente :boolean          default(FALSE), not null
#  boleta        :string(255)
#  total         :float
#

class Sale < ActiveRecord::Base
  belongs_to :cajero
  belongs_to :cliente
  belongs_to :medioPago
  belongs_to :user

  has_many :productosales
  has_many :productos, through: :productosale

  accepts_nested_attributes_for :productosales, allow_destroy: true
end

app/models/stock.rb
# == Schema Information
#
# Table name: stocks
#
#  id              :integer          not null, primary key
#  articulo_id     :integer
#  cantidad        :float
#  precio_unitario :float
#  precio_total    :float
#  user_id         :integer
#  empresa_id      :integer
#  fecha_compra    :date
#  created_at      :datetime
#  updated_at      :datetime
#

class Stock < ActiveRecord::Base
  belongs_to :articulo
  belongs_to :user
  belongs_to :empresa
end

app/models/tipo_producto.rb
# == Schema Information
#
# Table name: tipo_productos
#
#  id         :integer          not null, primary key
#  nombre     :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class TipoProducto < ActiveRecord::Base
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  name                   :string(255)
#  nombre                 :string(255)
#  empresa_id             :integer
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :empresa
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/helpers/cajeros_helper.rb
module CajerosHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
            <p>Copyright &copy; 2013. All Right Reserved.</p>
        </footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav.html.erb
  <!-- side left, its part to menu on left-->
            <div id="navside" class="side-left" data-collapse="navbar">
                <form class="form-inline search-module" action="?" method="post" />
                    <div class="input-append input-append-inline">
                        <input name="search" class="input-block-level" type="text" placeholder="buscar" />
                        <button class="btn bg-cyan" type="button">
                            <i class="aweso-search"></i>
                        </button>
                    </div>
                </form>
                <!--nav, this structure create with nav (find the bootstrap doc about .nav list) -->
                <ul class="nav nav-list">
                    
                    <li class="dropdown-list">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown-list">
                            Ventas 
                        </a>
                        <ul class="dropdown-menu">
                            <li><%= link_to "Listado Ventas", sales_path %></li>
                            <li><%= link_to "Medio de Pago", medio_pagos_path %></li>
                
                        </ul>
                    </li>

                    
                    <li><%= link_to "Inventario", stocks_path %></li>
                    <li><%= link_to "Proveedores", proveedors_path %></li>
                    <li><%= link_to "Colaboradores", colaboradors_path %></li>
                    <li><%= link_to "Clientes", clientes_path %></li>
                    <li class="dropdown-list">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown-list">
                            Productos 
                        </a>
                        <ul class="dropdown-menu">
                            <li><%= link_to "Listado Productos", productos_path %></li>
                            <li><%= link_to "Tipo Productos", tipo_productos_path %></li>
                
                        </ul>
                    </li>

                  
                </ul><!--/ nav -->
            </div><!--/ side left-->

app/views/layouts/_navigation.html.erb
<%= link_to "Ndpsige", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title><%= content_for?(:title) ? yield(:title) : "Ndpsige" %></title>
		<meta charset="utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=9" />
		
		
		<meta name="description" content="stilearn metro admin bootstrap" />
		<meta name="author" content="stilearning" />
		
		
		<%= stylesheet_link_tag "application", :media => "all" %>
	
		<%= csrf_meta_tags %>
		
		<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
		<script src="js/html5shiv.js"></script>
		<script src="js/lte-ie7.js"></script>
		<![endif]-->
		
		<!-- fav and touch icons -->
		<link rel="apple-touch-icon-precomposed" sizes="144x144" href="ico/apple-touch-icon-144-precomposed.png" />
		<link rel="apple-touch-icon-precomposed" sizes="114x114" href="ico/apple-touch-icon-114-precomposed.png" />
		<link rel="apple-touch-icon-precomposed" sizes="72x72" href="ico/apple-touch-icon-72-precomposed.png" />
		<link rel="apple-touch-icon-precomposed" href="ico/apple-touch-icon-57-precomposed.png" />
	
		<style>
		
		</style>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	</head>
	<body>
		<!-- start header-->
		<%= render 'layouts/header' %>
		
		<!-- start section content-->
		<section class="section-content">
			<%= render 'layouts/nav' %>
			
			
			
			<!-- start content -->
			<div class="content">
			<%= yield %>
			 </div><!--/ end content -->
			<!--/ end content -->
			</section> <!-- /end section content-->
			
			
			<!-- footer, I place the footer on here. -->
			<%= render 'layouts/footer' %>
			<!--/ footer -->
			
			
			<!-- required js -->
				<%= javascript_include_tag "application" %>


			

			
			<!-- datatables tabletools -->
			<script type="text/javascript" src="/js/datatables/jquery.dataTables.min.js"></script>
			<script type="text/javascript" src="/js/datatables/DT_bootstrap.js"></script>
			

			<!-- metro js, required! -->
	

			<!-- apps js -->
			<script type="text/javascript" src="/js/demo/dashboard4.js"></script>
		</body>
	</html>